# 100 numpy exercises (solved in Pytorch on tensors)

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the pytorch package (★☆☆)

In [3]:
import torch

#### 2. Print the pytorch version and the configuration (★☆☆)

In [48]:
print(torch.__version__)
print(torch.__config__)

1.13.1+cu117
<module 'torch.__config__' from '/home/milan/python_envs/Pytorch/lib/python3.8/site-packages/torch/__config__.py'>


#### 3. Create a null vector of size 10 (★☆☆)

In [49]:
empty = torch.zeros(10)
empty

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any tensor (★☆☆)

In [51]:
import sys
big_empty = torch.zeros(1000)

# This does not work:
print(sys.getsizeof(empty))
print(sys.getsizeof(big_empty))

# This does:
print(sys.getsizeof(empty.storage()))
print(sys.getsizeof(big_empty.storage()))


72
72
88
4048


#### 5. How to get the documentation of the pytorch stack function from the command line? (★☆☆)

In [134]:
help(torch.stack)

Help on built-in function stack in module torch:

stack(...)
    stack(tensors, dim=0, *, out=None) -> Tensor
    
    Concatenates a sequence of tensors along a new dimension.
    
    All tensors need to be of the same size.
    
    Arguments:
        tensors (sequence of Tensors): sequence of tensors to concatenate
        dim (int): dimension to insert. Has to be between 0 and the number
            of dimensions of concatenated tensors (inclusive)
    
    Keyword args:
        out (Tensor, optional): the output tensor.



#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [52]:
almost_empty = torch.zeros(10)
almost_empty[4] = 1
almost_empty

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [53]:
rng = torch.tensor(range(10, 50))
rng

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49])

In [54]:
rng = torch.arange(10, 50)
rng

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [55]:
torch.flip(rng, [0])

tensor([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
        31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
        13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [40]:
torch.arange(0, 9).view(3, 3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [39]:
torch.nonzero(torch.tensor([1,2,0,0,4,0]))

tensor([[0],
        [1],
        [4]])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [38]:
torch.eye(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [44]:
torch.rand(3, 3, 3)

tensor([[[0.0141, 0.6565, 0.0554],
         [0.5791, 0.6310, 0.4416],
         [0.4230, 0.3360, 0.4666]],

        [[0.1394, 0.6594, 0.0930],
         [0.8363, 0.3906, 0.0889],
         [0.2356, 0.3567, 0.2737]],

        [[0.5224, 0.1891, 0.9066],
         [0.0246, 0.6474, 0.8674],
         [0.2533, 0.7583, 0.7782]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [57]:
data = torch.rand(10, 10)
max = torch.max(data)
min = torch.min(data)
print(f"{data}\nmax: {max}\nmin: {min}")

tensor([[0.2339, 0.1693, 0.5955, 0.8616, 0.8792, 0.0468, 0.9530, 0.3881, 0.8315,
         0.7349],
        [0.6844, 0.4547, 0.7228, 0.4351, 0.5829, 0.1039, 0.1781, 0.0419, 0.4035,
         0.4767],
        [0.2093, 0.4248, 0.7643, 0.5706, 0.8255, 0.9792, 0.5763, 0.5863, 0.7707,
         0.7030],
        [0.1237, 0.5233, 0.2046, 0.2765, 0.8745, 0.0176, 0.2543, 0.1432, 0.5539,
         0.4180],
        [0.9722, 0.9808, 0.6138, 0.6995, 0.2587, 0.7723, 0.0898, 0.7990, 0.9600,
         0.2311],
        [0.7696, 0.6646, 0.1259, 0.8184, 0.8846, 0.1850, 0.8557, 0.4088, 0.5893,
         0.4795],
        [0.0500, 0.3409, 0.8942, 0.6911, 0.9479, 0.8869, 0.2375, 0.8948, 0.7302,
         0.5808],
        [0.6337, 0.7078, 0.7539, 0.2139, 0.3182, 0.2044, 0.9414, 0.0569, 0.1124,
         0.2778],
        [0.2524, 0.8197, 0.9720, 0.6900, 0.1458, 0.9770, 0.1809, 0.0705, 0.2203,
         0.1286],
        [0.1119, 0.8779, 0.4541, 0.1535, 0.5493, 0.7238, 0.5814, 0.4024, 0.7783,
         0.7357]])
max: 0.98

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [58]:
data = torch.rand(30)
torch.mean(data)

tensor(0.4471)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [87]:
torch.tensor([[1, 1, 1], [1, 0, 1], [1, 1, 1]])

tensor([[1, 1, 1],
        [1, 0, 1],
        [1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [79]:
def add_zeros_border(matrix):
    size = matrix.size()
    side = torch.zeros(1, size[1])
    top_and_botom = torch.zeros(size[0] + 2, 1)
    with_sides = torch.cat((side, matrix, side), 0)
    out_matrix = torch.cat((top_and_botom, with_sides, top_and_botom), 1)
    return out_matrix

In [81]:
add_zeros_border(torch.ones(2,2))

tensor([[0., 0., 0., 0.],
        [0., 1., 1., 0.],
        [0., 1., 1., 0.],
        [0., 0., 0., 0.]])

In [82]:
add_zeros_border(torch.rand(5,5))

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.8998, 0.3485, 0.5678, 0.0884, 0.6537, 0.0000],
        [0.0000, 0.9473, 0.1529, 0.2094, 0.1915, 0.3398, 0.0000],
        [0.0000, 0.4702, 0.4017, 0.0522, 0.7953, 0.8566, 0.0000],
        [0.0000, 0.0552, 0.0593, 0.1072, 0.8382, 0.8809, 0.0000],
        [0.0000, 0.7342, 0.2141, 0.9759, 0.0238, 0.4346, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# not applicable

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [110]:
matrix = torch.diag(torch.arange(1, 5))
matrix = torch.cat((matrix, torch.zeros(4, 1)), 1)
matrix = torch.cat((torch.zeros(1, 5), matrix), 0)
matrix

tensor([[0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0.],
        [0., 0., 3., 0., 0.],
        [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [140]:
vector = torch.tensor([0, 1])
for _ in range(2):
    vector = torch.cat((vector, vector), 0)

matrix = []
for _ in range(6):
    matrix.append(vector)
    vector = torch.flip(vector, [0])

matrix = torch.stack(matrix, 0)
matrix

tensor([[0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [139]:
n_elements = 6 * 7 * 8
tensor = torch.arange(n_elements).view(6, 7, 8)
torch.nonzero(torch.where(tensor == 100, 1, 0))

tensor([[1, 5, 4]])

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)